"""Update models for Ludo MVP

Revision ID: 5b583064de70
Revises: 4b6cbdb5e73a
Create Date: 2025-08-27 11:03:11.166148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b583064de70'
down_revision: Union[str, Sequence[str], None] = '4b6cbdb5e73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('player_order', sa.Integer(), nullable=False),
    sa.Column('token_positions', sa.JSON(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_players_id'), 'game_players', ['id'], unique=False)
    op.add_column('games', sa.Column('current_player_turn', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'games', 'players', ['winner_id'], ['id'])
    op.drop_column('games', 'current_player')
    op.drop_column('games', 'player_count')
    op.add_column('players', sa.Column('games_played', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('games_won', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'players', ['name'])
    op.drop_column('players', 'color')
    op.drop_column('players', 'game_id')
    op.drop_column('players', 'is_winner')
    op.drop_column('players', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('is_winner', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players', type_='unique')
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('players', 'created_at')
    op.drop_column('players', 'games_won')
    op.drop_column('players', 'games_played')
    op.add_column('games', sa.Column('player_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('current_player', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'finished_at')
    op.drop_column('games', 'winner_id')
    op.drop_column('games', 'current_player_turn')
    op.drop_index(op.f('ix_game_players_id'), table_name='game_players')
    op.drop_table('game_players')
    # ### end Alembic commands ###
